linkedin_username: adaskin
github_username:  adaskin
orcid: 0000-0002-1497-5031

google_analytics: G-TK95NJTFFL


title: Grouping Set Elements on Quantum Computers
email: adaskin25@gmail.com

baseurl: "/quantum-grouping-set-elements" # the subpath of your site, e.g. /blog
url: "https://adaskin.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  adaskin

# Build settings
theme: minima
plugins:
  - jekyll-feed

include:
  - _includes
  - _images
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
